# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - "Build"
  - "Package"

# ----------------------------------------
# Build
# ----------------------------------------

compile-site:
  stage: "Build"
  image: alpine:latest
  script:
    - sh build/build.sh

# ----------------------------------------
# Package
# ----------------------------------------

package-as-zip:
  stage: "Package"
  image: alpine:latest
  script:
    - apk add --update zip
    - sh build/package.sh
  artifacts:
    expire_in: 4 weeks
    paths:
      - wifi-web*.zip