# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - "Build"
  - "Deploy"

# ----------------------------------------
# Build
# ----------------------------------------

build:
  stage: "Build"
  image: alpine:latest
  script:
    - sh build/build.sh
  only:
    - web
    - develop
    - master

# ----------------------------------------
# Deploy
# ----------------------------------------

deploy:
  stage: "Deploy"
  image: alpine:latest
  script:
    - apk add -U zip
    - sh build/package.sh
  artifacts:
    expire_in: 4 weeks
    paths:
      - wifi-web*.zip
  only:
    - web
    - develop
    - master